name = "MultivariateMixtures"
uuid = "9918c206-6723-4052-8484-be78ce6c49bd"
keywords = ["multivariate statistics", "mixtures"]
license = "MIT"
desc = "A Julia package for multivariate mixture models"
repository = "https://github.com/wildart/MultivariateMixtures.jl.git"
version = "0.3.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "^0.23"
MultivariateStats = "^0.7"
StatsBase = "^0.33"
julia = "≥ 1.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MultivariateStats", "Distributions"]
